name: ci-golang
on:
  pull_request:
    branches:
      - develop
jobs:
  checkout-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: go test
      - run: go run math.go

        name: Set up QEMU
      - uses: docker/setup-qemu-action@v3
        
        name: Set up Docker Buildx
      - uses: docker/setup-buildx-action@v3

        name: Login to Docker Hub
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        name: Build and push
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: joaoparaujo/golang-fc:latest